import { Header } from "@/components/trading/Header";
import { SEOHead } from "@/components/seo/SEOHead";
import { Card, CardContent } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Zap, Shield, BarChart3, Globe, Users, Bot } from "lucide-react";

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Botvio",
  url: "https://botvio.live",
  logo: "https://botvio.live/icon-512.png",
  description:
    "AI-powered forex signals, gold trading mentorship, chart analysis tools and automated trading bots for Deriv, Exness, Weltrade & Binance.",
  foundingDate: "2024",
  sameAs: [
    "https://t.me/boaborea",
    "https://www.tiktok.com/@botviohq",
    "https://whatsapp.com/channel/0029VbAfFXbIT6Kbng6ypX0V",
  ],
};

const values = [
  { icon: Bot, title: "AI-Powered Signals", desc: "Real-time trading signals generated by advanced machine-learning models across forex, gold, synthetic indices, and crypto." },
  { icon: BarChart3, title: "Chart Analysis", desc: "Upload any chart and receive instant AI-driven technical analysis — support/resistance levels, pattern recognition, and trade ideas." },
  { icon: Shield, title: "Risk Management", desc: "Built-in guardrails including position-sizing calculators, stop-loss recommendations, and daily drawdown limits." },
  { icon: Globe, title: "Multi-Broker Support", desc: "Seamlessly connect with Deriv, Exness, Weltrade, and Binance from a single dashboard." },
  { icon: Users, title: "Copy Trading", desc: "Follow top-performing signal providers and automatically replicate their trades on your own account." },
  { icon: Zap, title: "Education & Academy", desc: "100+ free articles, video guides, and strategy breakdowns to help traders of all levels improve consistently." },
];

const About = () => (
  <div className="min-h-screen bg-background">
    <SEOHead seoKey="about"
      title="About Botvio – AI Trading Signals & Forex Education"
      description="Botvio is an AI-powered trading platform providing free forex signals, chart analysis, gold trading tools, and education for traders worldwide."
      jsonLd={jsonLd}
    />
    <Header />

    <main className="container mx-auto max-w-4xl px-4 py-12">
      <h1 className="text-3xl font-bold sm:text-4xl">About Botvio</h1>
      <p className="mt-3 text-lg text-muted-foreground leading-relaxed">
        Botvio is an AI-powered trading platform built to help traders make
        smarter, faster, and more consistent decisions. Founded in 2024, we
        serve thousands of traders across Africa, Asia, and beyond — providing
        free forex signals, gold analysis, chart AI tools, and a growing
        educational academy.
      </p>

      <Separator className="my-8" />

      {/* Mission */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Our Mission</h2>
        <p className="text-muted-foreground leading-relaxed">
          We believe every trader — regardless of experience or location —
          deserves access to institutional-grade analysis tools. Our mission is
          to democratize trading intelligence by combining artificial
          intelligence with practical education, so that anyone with a phone and
          an internet connection can trade with confidence.
        </p>
      </section>

      {/* What We Offer */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-5">What We Offer</h2>
        <div className="grid gap-4 sm:grid-cols-2">
          {values.map((v) => (
            <Card key={v.title} className="border-border bg-card">
              <CardContent className="flex gap-4 p-5">
                <v.icon className="mt-1 h-6 w-6 shrink-0 text-primary" />
                <div>
                  <h3 className="font-semibold text-foreground">{v.title}</h3>
                  <p className="mt-1 text-sm text-muted-foreground">{v.desc}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Team */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Our Team</h2>
        <p className="text-muted-foreground leading-relaxed">
          Botvio is built by a small, passionate team of traders, developers,
          and data scientists who understand the challenges of retail trading
          first-hand. We combine deep market knowledge with cutting-edge AI
          research to create tools that actually work in live market conditions.
        </p>
      </section>

      {/* Transparency */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-3">Transparency & Trust</h2>
        <p className="text-muted-foreground leading-relaxed">
          We are committed to honest, transparent communication. Trading
          involves risk, and we never guarantee profits. Our signal performance
          is tracked publicly, and we encourage every user to start with a demo
          account before risking real capital. Read our{" "}
          <Link to="/disclaimer" className="text-primary underline">
            Disclaimer
          </Link>{" "}
          and{" "}
          <Link to="/privacy" className="text-primary underline">
            Privacy Policy
          </Link>{" "}
          for full details.
        </p>
      </section>

      {/* CTA */}
      <div className="flex flex-wrap gap-3">
        <Link to="/">
          <Button variant="gold" size="lg">Get Started Free</Button>
        </Link>
        <Link to="/blog">
          <Button variant="outline" size="lg">Read Our Blog</Button>
        </Link>
        <Link to="/contact">
          <Button variant="outline" size="lg">Contact Us</Button>
        </Link>
      </div>
    </main>
  </div>
);

export default About;
