import { SEOHead } from "@/components/seo/SEOHead";
import { Header } from "@/components/trading/Header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Link } from "react-router-dom";
import { TrendingUp, TrendingDown, Clock, Zap, Target, Award, BarChart3 } from "lucide-react";
import { useBotvioSignals, type Signal } from "@/hooks/useBotvioSignals";
import { useManualSignals } from "@/hooks/useManualSignals";

const AuthoritySignals = () => {
  const { signals, loading } = useBotvioSignals("XAUUSD", "M5");
  const { data: manualSignals, isLoading: manualLoading } = useManualSignals();

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Botvio Authority Signals",
    description: "AI-generated and expert trading signals for Deriv synthetic indices. Real-time signals with confidence scores.",
    url: "https://botvio.live/authority-signals",
  };

  return (
    <div className="min-h-screen bg-background">
      <SEOHead title="Authority Signals" description="Real-time AI-generated and expert trading signals for Deriv. High-confidence signals with performance tracking and analysis." jsonLd={jsonLd} />
      <Header />
      <main className="container mx-auto px-4 py-10 space-y-8">
        <div className="text-center space-y-3">
          <Badge className="text-sm px-3 py-1"><Zap className="h-3 w-3 mr-1" /> Live Signals</Badge>
          <h1 className="text-4xl font-extrabold tracking-tight">Botvio Authority Signals</h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">AI-generated trading signals powered by Botvio's AI engine. Every signal includes confidence scores, reasoning, and real-time tracking.</p>
        </div>

        <div className="grid sm:grid-cols-3 gap-4">
          <Card><CardContent className="pt-5 text-center"><BarChart3 className="h-8 w-8 mx-auto text-primary mb-2" /><p className="text-2xl font-bold">{signals.length + (manualSignals?.length || 0)}</p><p className="text-xs text-muted-foreground">Total Signals</p></CardContent></Card>
          <Card><CardContent className="pt-5 text-center"><Target className="h-8 w-8 mx-auto text-primary mb-2" /><p className="text-2xl font-bold">8</p><p className="text-xs text-muted-foreground">Trading Modes</p></CardContent></Card>
          <Card><CardContent className="pt-5 text-center"><Award className="h-8 w-8 mx-auto text-primary mb-2" /><p className="text-2xl font-bold">24/7</p><p className="text-xs text-muted-foreground">AI Monitoring</p></CardContent></Card>
        </div>

        <Tabs defaultValue="ai">
          <TabsList>
            <TabsTrigger value="ai">AI Signals</TabsTrigger>
            <TabsTrigger value="community">Community Signals</TabsTrigger>
          </TabsList>

          <TabsContent value="ai" className="space-y-4 mt-4">
            {loading ? (
              <p className="text-center text-muted-foreground py-8">Loading signals...</p>
            ) : signals.length === 0 ? (
              <Card><CardContent className="py-8 text-center text-muted-foreground">No AI signals available yet. Signals are generated when the Botvio Sniper engine detects high-probability setups.</CardContent></Card>
            ) : (
              signals.map(s => (
                <Card key={s.id}>
                  <CardContent className="py-4 flex items-center gap-4 flex-wrap">
                    <div className="flex items-center gap-2">
                      {s.direction === "BUY" ? <TrendingUp className="h-5 w-5 text-primary" /> : <TrendingDown className="h-5 w-5 text-destructive" />}
                      <Badge variant={s.direction === "BUY" ? "default" : "destructive"}>{s.direction}</Badge>
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold">{s.symbol} — {s.strategy_name}</p>
                      <p className="text-xs text-muted-foreground">{s.reason || "Signal generated by Botvio AI engine"}</p>
                    </div>
                    <div className="flex items-center gap-4 text-sm">
                      <span>Entry: ${s.entry_price.toFixed(2)}</span>
                      {s.stop_loss && <span className="text-muted-foreground">SL: ${s.stop_loss.toFixed(2)}</span>}
                      {s.take_profit && <span className="text-muted-foreground">TP: ${s.take_profit.toFixed(2)}</span>}
                      {s.confidence && <Badge variant="outline">{s.confidence}% conf</Badge>}
                    </div>
                    <span className="text-xs text-muted-foreground flex items-center gap-1"><Clock className="h-3 w-3" />{new Date(s.created_at).toLocaleString()}</span>
                  </CardContent>
                </Card>
              ))
            )}
          </TabsContent>

          <TabsContent value="community" className="space-y-4 mt-4">
            {manualLoading ? (
              <p className="text-center text-muted-foreground py-8">Loading community signals...</p>
            ) : !manualSignals || manualSignals.length === 0 ? (
              <Card><CardContent className="py-8 text-center text-muted-foreground">No community signals yet. Signal managers can post signals from the Signals page.</CardContent></Card>
            ) : (
              manualSignals.map((s: any) => (
                <Card key={s.id}>
                  <CardContent className="py-4 flex items-center gap-4 flex-wrap">
                    <Badge variant={s.direction === "BUY" ? "default" : "destructive"}>{s.direction}</Badge>
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold">{s.symbol} — {s.timeframe}</p>
                      <p className="text-xs text-muted-foreground">{s.analysis || "Community signal"}</p>
                    </div>
                    <span className="text-xs text-muted-foreground">{new Date(s.created_at).toLocaleString()}</span>
                  </CardContent>
                </Card>
              ))
            )}
          </TabsContent>
        </Tabs>

        <div className="text-center space-y-3 py-6">
          <h2 className="text-2xl font-bold">Want Automated Signal Execution?</h2>
          <p className="text-muted-foreground">Enable Botvio's Auto Mode to execute signals automatically.</p>
          <Link to="/"><Button size="lg">Start Trading with Botvio</Button></Link>
        </div>
      </main>
    </div>
  );
};

export default AuthoritySignals;
