import { Link } from "react-router-dom";
import { ArrowRight, Activity, BookOpen, ShieldCheck } from "lucide-react";
import { SEOHead } from "@/components/seo/SEOHead";
import { Header } from "@/components/trading/Header";
import { AffiliateAccountGuide } from "@/components/affiliate/AffiliateAccountGuide";

const DERIV_SIGNUP="https://track.deriv.com/_a_gq1w0BG0D1hit6RV3zsGNd7ZgqdRLk/1/";
const markets=[
["Volatility 10","volatility-10-trading-dubai"],["Volatility 25","volatility-25-trading-dubai"],["Volatility 50","volatility-50-trading-dubai"],["Volatility 75","volatility-75-dubai-guide"],["Volatility 100","volatility-100-trading-dubai"],["Volatility 150","volatility-150-trading-dubai"],["Boom 500","boom-500-trading-dubai"],["Boom 1000","boom-1000-trading-dubai"],["Crash 500","crash-500-trading-dubai"],["Crash 1000","crash-1000-trading-dubai"],["Step Index","step-index-trading-dubai"],["Synthetic Indices","synthetic-indices-dubai-guide"]
];
export default function SyntheticIndicesGuideHub(){return <div className="min-h-screen bg-background"><SEOHead title="Synthetic Indices Guide — Volatility, Boom, Crash & Step | BOTVIO" description="BOTVIO's public synthetic indices research hub with market explainers, Dubai guides, risk education and Deriv account onboarding."/><Header/><main className="container mx-auto px-4 py-8">
<section className="rounded-3xl border bg-card p-6 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[.18em] text-primary">Synthetic indices research</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">Synthetic Indices Guide</h1><p className="mt-4 max-w-3xl text-muted-foreground">Explore Volatility, Boom, Crash and Step Index research. BOTVIO focuses on market structure, chart research and risk controls rather than guaranteed outcomes.</p><div className="mt-6 grid gap-3 md:grid-cols-3"><div className="rounded-2xl border p-4"><Activity className="h-5 w-5 text-primary"/><h2 className="mt-2 font-semibold">Market research</h2><p className="text-sm text-muted-foreground">Understand instrument behaviour before building a strategy.</p></div><div className="rounded-2xl border p-4"><BookOpen className="h-5 w-5 text-primary"/><h2 className="mt-2 font-semibold">Education</h2><p className="text-sm text-muted-foreground">Use guides, examples and checklists to build a repeatable process.</p></div><div className="rounded-2xl border p-4"><ShieldCheck className="h-5 w-5 text-primary"/><h2 className="mt-2 font-semibold">Risk first</h2><p className="text-sm text-muted-foreground">Historical behaviour is not a promise of future results.</p></div></div></section>
<section className="mt-8"><h2 className="text-2xl font-bold">Instrument research</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{markets.map(([name,slug])=><Link key={slug} to={`/blog/${slug}`} className="group rounded-2xl border bg-card p-5 hover:border-primary/40"><h3 className="font-bold">{name}</h3><p className="mt-2 text-sm text-muted-foreground">Read the research guide</p><span className="mt-4 inline-flex items-center gap-1 text-sm text-primary">Open guide <ArrowRight className="h-4 w-4"/></span></Link>)}</div></section>
<section className="mt-8"><AffiliateAccountGuide broker="deriv" affiliateUrl={DERIV_SIGNUP}/></section>
<p className="mt-6 text-xs leading-5 text-muted-foreground">Derivatives carry significant risk and may not be suitable for everyone. Availability, products and account conditions vary by jurisdiction and provider. Use current provider documentation.</p>
</main></div>}
