import { supabase } from "@/integrations/supabase/client";

const VISITOR_KEY="botvio_visitor_id";
const SESSION_KEY="botvio_session_id";
const makeId=()=>Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,10);
const storage=(key:string)=>{try{return localStorage.getItem(key)}catch{return null}};
const setStorage=(key:string,value:string)=>{try{localStorage.setItem(key,value)}catch{}};
function deviceType(){const ua=navigator.userAgent.toLowerCase();if(/tablet|ipad|playbook|silk/.test(ua)||(navigator.maxTouchPoints>1&&/macintosh/.test(ua)))return "tablet";if(/mobile|android|iphone|ipod|windows phone/.test(ua))return "mobile";return "desktop";}
function sourceFrom(referrer:string){if(!referrer)return "Direct";try{const host=new URL(referrer).hostname.replace(/^www\./,"");if(host===location.hostname)return "Internal";if(/chatgpt\.com$/.test(host))return "AI Search";if(/perplexity\.ai$/.test(host))return "AI Search";if(/gemini\.google\.com$/.test(host))return "AI Search";if(/copilot\.microsoft\.com$/.test(host))return "AI Search";if(/google\./.test(host))return "Google";if(/bing\.com$/.test(host))return "Bing";if(/facebook|instagram|tiktok|linkedin|youtube|twitter|x\.com/.test(host))return "Social";if(/lovable/.test(host))return "Lovable";return host;}catch{return "Referral";}}
export function trackBotvioEvent(event_name:string,metadata:Record<string,unknown>={}){const visitor=storage(VISITOR_KEY)||makeId();const session=storage(SESSION_KEY)||makeId();setStorage(VISITOR_KEY,visitor);setStorage(SESSION_KEY,session);const params=new URLSearchParams(location.search);const referrer=document.referrer||"";return (supabase as any).from("analytics_events").insert({event_name,visitor_id:visitor,session_id:session,path:location.pathname,referrer,source:sourceFrom(referrer),medium:params.get("utm_medium"),campaign:params.get("utm_campaign")||params.get("utm_source"),device_type:deviceType(),metadata});}
export { VISITOR_KEY, SESSION_KEY, makeId, storage, setStorage, deviceType, sourceFrom };