export interface CountryInfo {
  name: string;
  flag: string;
  metaDescription: string;
  heroText: string;
  whyContent: string;
  popularStrategies: { name: string; description: string }[];
  gettingStarted: string;
  localPayments?: string;
}

const defaultStrategies = [
  { name: "Boom/Crash Spike Trading", description: "Botvio detects spike droughts on Boom 1000, 500, and Crash indices for high-probability entries." },
  { name: "Digit Match/Differ", description: "Botvio's Markov transition engine predicts last-digit patterns for Match and Differ contracts." },
  { name: "Rise/Fall Scalping", description: "Botvio uses EMA 9/21 crossovers to capture short-term directional moves." },
  { name: "Accumulator Growth", description: "Botvio identifies low-volatility phases for steady accumulator contract growth." },
];

function makeCountry(name: string, flag: string, extras?: Partial<CountryInfo>): CountryInfo {
  return {
    name, flag,
    metaDescription: `Use Botvio AI trading bot in ${name} to automate Deriv synthetic indices trading. 8 trading modes, encrypted security, 24/7 execution.`,
    heroText: `${name}'s fastest-growing AI trading platform. Botvio automates Deriv synthetic indices trading with advanced algorithms, giving ${name} traders a competitive edge.`,
    whyContent: `<p>Traders in ${name} are increasingly turning to Botvio for automated trading on Deriv. Botvio's AI-powered signal engines work 24/7, analyzing tick data and executing trades even while you sleep.</p><p>Botvio is especially popular in ${name} because of its low minimum stake requirements, mobile-friendly interface, and support for local payment methods. Whether you're a beginner or experienced trader in ${name}, Botvio adapts to your style.</p><p>Botvio's AI strategy suite was developed with emerging market traders in mind, offering reliable performance on Deriv's synthetic indices that are available around the clock.</p>`,
    popularStrategies: defaultStrategies,
    gettingStarted: `<ol><li>Create your free Botvio account</li><li>Connect your Deriv trading account via OAuth</li><li>Choose from 8 trading modes (Digits, Multipliers, Rise/Fall, Boom/Crash, Ticks, Accumulators, Turbo, Higher/Lower)</li><li>Set your stake and risk limits in Botvio</li><li>Enable Auto Mode and let Botvio trade for you</li></ol><p>Botvio offers a free starter plan — no payment required to begin.</p>`,
    ...extras,
  };
}

export const countryData: Record<string, CountryInfo> = {
  // Africa
  nigeria: makeCountry("Nigeria", "🇳🇬", { localPayments: "Botvio supports payments via mobile money, crypto (USDT TRC20, Bitcoin), and bank transfer for Nigerian traders." }),
  zambia: makeCountry("Zambia", "🇿🇲", { localPayments: "Zambian traders can fund via Airtel Money, MTN Mobile Money, and crypto wallets." }),
  kenya: makeCountry("Kenya", "🇰🇪", { localPayments: "M-Pesa, Airtel Money, and crypto payments are available for Kenyan Botvio users." }),
  ghana: makeCountry("Ghana", "🇬🇭", { localPayments: "Mobile Money (MTN, Vodafone Cash) and crypto payments available." }),
  "south-africa": makeCountry("South Africa", "🇿🇦", { localPayments: "EFT, bank cards, and crypto payments supported for South African traders." }),
  tanzania: makeCountry("Tanzania", "🇹🇿", { localPayments: "M-Pesa Tanzania, Tigo Pesa, and crypto wallets supported." }),
  uganda: makeCountry("Uganda", "🇺🇬", { localPayments: "MTN Mobile Money Uganda, Airtel Money, and crypto payments available." }),
  zimbabwe: makeCountry("Zimbabwe", "🇿🇼", { localPayments: "EcoCash, crypto payments, and bank transfers supported." }),
  mozambique: makeCountry("Mozambique", "🇲🇿", { localPayments: "M-Pesa Mozambique, e-Mola, and crypto wallets available." }),
  cameroon: makeCountry("Cameroon", "🇨🇲", { localPayments: "MTN MoMo, Orange Money, and crypto payments supported." }),
  "ivory-coast": makeCountry("Ivory Coast", "🇨🇮", { localPayments: "Orange Money, MTN Mobile Money, and Wave payments available." }),
  senegal: makeCountry("Senegal", "🇸🇳", { localPayments: "Orange Money, Wave, and crypto wallets supported." }),
  ethiopia: makeCountry("Ethiopia", "🇪🇹"),
  rwanda: makeCountry("Rwanda", "🇷🇼", { localPayments: "MTN MoMo Rwanda and Airtel Money available." }),
  malawi: makeCountry("Malawi", "🇲🇼", { localPayments: "Airtel Money Malawi and TNM Mpamba available." }),
  botswana: makeCountry("Botswana", "🇧🇼", { localPayments: "Bank cards, Orange Money, and crypto payments available." }),
  namibia: makeCountry("Namibia", "🇳🇦", { localPayments: "Bank transfers, FNB eWallet, and crypto payments available." }),
  madagascar: makeCountry("Madagascar", "🇲🇬"),
  "democratic-republic-of-congo": makeCountry("DR Congo", "🇨🇩", { localPayments: "M-Pesa DRC, Airtel Money, and Orange Money available." }),
  angola: makeCountry("Angola", "🇦🇴"),
  "burkina-faso": makeCountry("Burkina Faso", "🇧🇫", { localPayments: "Orange Money and Moov Money available." }),
  mali: makeCountry("Mali", "🇲🇱", { localPayments: "Orange Money Mali and crypto wallets available." }),
  niger: makeCountry("Niger", "🇳🇪"),
  guinea: makeCountry("Guinea", "🇬🇳", { localPayments: "Orange Money Guinea and MTN MoMo available." }),
  benin: makeCountry("Benin", "🇧🇯", { localPayments: "MTN MoMo and Moov Money available." }),
  togo: makeCountry("Togo", "🇹🇬", { localPayments: "Flooz and T-Money available." }),
  "sierra-leone": makeCountry("Sierra Leone", "🇸🇱"),
  liberia: makeCountry("Liberia", "🇱🇷"),
  "south-sudan": makeCountry("South Sudan", "🇸🇸"),
  sudan: makeCountry("Sudan", "🇸🇩"),
  somalia: makeCountry("Somalia", "🇸🇴"),
  eritrea: makeCountry("Eritrea", "🇪🇷"),
  gabon: makeCountry("Gabon", "🇬🇦"),
  lesotho: makeCountry("Lesotho", "🇱🇸"),
  eswatini: makeCountry("Eswatini", "🇸🇿"),
  mauritius: makeCountry("Mauritius", "🇲🇺"),
  "cape-verde": makeCountry("Cape Verde", "🇨🇻"),
  gambia: makeCountry("Gambia", "🇬🇲"),
  "equatorial-guinea": makeCountry("Equatorial Guinea", "🇬🇶"),
  chad: makeCountry("Chad", "🇹🇩"),
  "central-african-republic": makeCountry("Central African Republic", "🇨🇫"),
  // Asia
  india: makeCountry("India", "🇮🇳", { localPayments: "UPI, bank transfer, and crypto payments supported for Indian traders." }),
  pakistan: makeCountry("Pakistan", "🇵🇰", { localPayments: "JazzCash, Easypaisa, and bank transfers available." }),
  bangladesh: makeCountry("Bangladesh", "🇧🇩", { localPayments: "bKash, Nagad, and bank transfers supported." }),
  philippines: makeCountry("Philippines", "🇵🇭", { localPayments: "GCash, Maya, and bank transfers available." }),
  indonesia: makeCountry("Indonesia", "🇮🇩", { localPayments: "GoPay, OVO, Dana, and bank transfers supported." }),
  malaysia: makeCountry("Malaysia", "🇲🇾", { localPayments: "Touch 'n Go, Boost, and bank transfers available." }),
  vietnam: makeCountry("Vietnam", "🇻🇳", { localPayments: "MoMo, ZaloPay, and bank transfers supported." }),
  thailand: makeCountry("Thailand", "🇹🇭", { localPayments: "PromptPay, TrueMoney, and bank transfers available." }),
  "sri-lanka": makeCountry("Sri Lanka", "🇱🇰", { localPayments: "Bank transfers and crypto payments supported." }),
  nepal: makeCountry("Nepal", "🇳🇵", { localPayments: "eSewa, Khalti, and bank transfers available." }),
  myanmar: makeCountry("Myanmar", "🇲🇲"),
  cambodia: makeCountry("Cambodia", "🇰🇭", { localPayments: "Wing, ABA Pay, and crypto payments available." }),
  uzbekistan: makeCountry("Uzbekistan", "🇺🇿"),
  kazakhstan: makeCountry("Kazakhstan", "🇰🇿"),
  azerbaijan: makeCountry("Azerbaijan", "🇦🇿"),
  georgia: makeCountry("Georgia", "🇬🇪"),
  tajikistan: makeCountry("Tajikistan", "🇹🇯"),
  kyrgyzstan: makeCountry("Kyrgyzstan", "🇰🇬"),
  mongolia: makeCountry("Mongolia", "🇲🇳"),
  laos: makeCountry("Laos", "🇱🇦"),
  // Latin America
  brazil: makeCountry("Brazil", "🇧🇷", { localPayments: "PIX, Boleto, and bank transfers supported for Brazilian traders." }),
  mexico: makeCountry("Mexico", "🇲🇽", { localPayments: "SPEI, OXXO, and bank transfers available." }),
  colombia: makeCountry("Colombia", "🇨🇴", { localPayments: "PSE, Nequi, and bank transfers supported." }),
  argentina: makeCountry("Argentina", "🇦🇷", { localPayments: "Mercado Pago, bank transfers, and crypto available." }),
  peru: makeCountry("Peru", "🇵🇪", { localPayments: "Yape, Plin, and bank transfers available." }),
  chile: makeCountry("Chile", "🇨🇱"),
  ecuador: makeCountry("Ecuador", "🇪🇨"),
  venezuela: makeCountry("Venezuela", "🇻🇪", { localPayments: "Crypto (USDT, Bitcoin) and P2P transfers supported." }),
  "dominican-republic": makeCountry("Dominican Republic", "🇩🇴"),
  guatemala: makeCountry("Guatemala", "🇬🇹"),
  honduras: makeCountry("Honduras", "🇭🇳"),
  "el-salvador": makeCountry("El Salvador", "🇸🇻"),
  panama: makeCountry("Panama", "🇵🇦"),
  "costa-rica": makeCountry("Costa Rica", "🇨🇷"),
  bolivia: makeCountry("Bolivia", "🇧🇴"),
  paraguay: makeCountry("Paraguay", "🇵🇾"),
  uruguay: makeCountry("Uruguay", "🇺🇾"),
  nicaragua: makeCountry("Nicaragua", "🇳🇮"),
  // Middle East & North Africa
  egypt: makeCountry("Egypt", "🇪🇬", { localPayments: "Fawry, Vodafone Cash, and bank transfers supported." }),
  morocco: makeCountry("Morocco", "🇲🇦"),
  tunisia: makeCountry("Tunisia", "🇹🇳"),
  "saudi-arabia": makeCountry("Saudi Arabia", "🇸🇦"),
  uae: makeCountry("UAE", "🇦🇪"),
  jordan: makeCountry("Jordan", "🇯🇴"),
  iraq: makeCountry("Iraq", "🇮🇶"),
  lebanon: makeCountry("Lebanon", "🇱🇧"),
  oman: makeCountry("Oman", "🇴🇲"),
  bahrain: makeCountry("Bahrain", "🇧🇭"),
  qatar: makeCountry("Qatar", "🇶🇦"),
  kuwait: makeCountry("Kuwait", "🇰🇼"),
  algeria: makeCountry("Algeria", "🇩🇿"),
  libya: makeCountry("Libya", "🇱🇾"),
  // Europe / CIS
  turkey: makeCountry("Turkey", "🇹🇷", { localPayments: "Bank transfers, Papara, and crypto available." }),
  ukraine: makeCountry("Ukraine", "🇺🇦"),
  poland: makeCountry("Poland", "🇵🇱"),
  romania: makeCountry("Romania", "🇷🇴"),
  serbia: makeCountry("Serbia", "🇷🇸"),
  "north-macedonia": makeCountry("North Macedonia", "🇲🇰"),
  albania: makeCountry("Albania", "🇦🇱"),
  "bosnia-herzegovina": makeCountry("Bosnia and Herzegovina", "🇧🇦"),
  moldova: makeCountry("Moldova", "🇲🇩"),
  armenia: makeCountry("Armenia", "🇦🇲"),
  // Caribbean
  jamaica: makeCountry("Jamaica", "🇯🇲"),
  "trinidad-and-tobago": makeCountry("Trinidad and Tobago", "🇹🇹"),
  haiti: makeCountry("Haiti", "🇭🇹"),
  barbados: makeCountry("Barbados", "🇧🇧"),
  bahamas: makeCountry("Bahamas", "🇧🇸"),
  // Oceania
  "papua-new-guinea": makeCountry("Papua New Guinea", "🇵🇬"),
  fiji: makeCountry("Fiji", "🇫🇯"),
};
