import { ReactNode, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Activity, ArrowRight, BarChart3, Bot, ChevronRight, Crown, History, House, Layers3, Link2, LogOut, Radio, Search, Settings, TrendingUp, Users, Wallet, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { NotificationBell } from "@/components/trading/NotificationBell";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { useAuth } from "@/contexts/AuthContext";
import accessArt from "@/assets/dashboard-access.jpg";
import "./trading-overview.css";

const links = [
  ["Overview", "/botvio-robot", House], ["My Hubs", "/my-products", Layers3], ["Trading Signals", "/signals", BarChart3],
  ["Deriv Options", "/options", Zap], ["Deriv MT5", "/connections", TrendingUp], ["Weltrade MT5", "/weltrade", Wallet],
  ["Provider Signals", "/provider-dashboard", Radio], ["Follow Providers", "/copy-trading/my", Users],
  ["Botvio Robot", "/bots", Bot], ["Trade History", "/trade-history", History], ["Settings", "/settings", Settings],
] as const;
export interface OverviewAccess { id: string; name: string; href: string; endsAt: string | null; slug?: string }
export interface OverviewAccount { id: string; label?: string | null; broker?: string | null; server?: string | null; login_id?: string | null; account_role?: string | null; environment?: string | null; connection_status?: string | null; tradecopy_active?: boolean | null }
export interface OverviewPosition { key: string; account: string; broker: string; symbol: string; side: string; volume: unknown; entry: unknown; current?: unknown; pnl: unknown; mock: boolean }
interface Props { access: OverviewAccess[]; accounts: OverviewAccount[]; positions: OverviewPosition[]; accessLoading: boolean; accountsLoading: boolean; positionLoading: boolean; accessError: boolean; accountsError: string | null; positionError: ReactNode; anyMock: boolean; retryAccess: () => void; retryAccounts: () => void; retryPositions: () => void; robotControls: ReactNode; children?: ReactNode }
const formatValue = (value: unknown) => value == null ? "—" : String(value);
const formatMoney = (value: number) => `${value >= 0 ? "+" : "−"}$${Math.abs(value).toFixed(2)}`;
export function TradingOverview(props: Props) {
  const { user, profile, signOut } = useAuth();
  const navigate = useNavigate();
  const [search, setSearch] = useState("");
  const name = profile?.display_name || "My account";
  const connected = props.accounts.filter(a => a.connection_status === "connected" || a.tradecopy_active).length;
  const verifiedPositions = props.positions.filter(p => !p.mock);
  const pnlAvailable = verifiedPositions.length > 0 && verifiedPositions.every(p => p.pnl != null && Number.isFinite(Number(p.pnl))) && !props.positionError;
  const pnl = verifiedPositions.reduce((sum, p) => sum + Number(p.pnl ?? 0), 0);
  const metrics = [
    { title: "Active Subscriptions", value: props.accessLoading ? "…" : props.accessError ? "—" : props.access.length, description: "Access to hubs, signals and robots", icon: Layers3, tone: "green" },
    { title: "Connected Accounts", value: props.accountsLoading ? "…" : props.accountsError ? "—" : connected, description: "Deriv MT5, Weltrade MT5", icon: Link2, tone: "cyan" },
    { title: "Open Positions", value: props.positionLoading ? "…" : props.positionError ? "—" : verifiedPositions.length, description: "Live trades across all accounts", icon: BarChart3, tone: "gold" },
    { title: "Floating P/L", value: props.positionLoading ? "…" : pnlAvailable ? formatMoney(pnl) : "—", description: "Verified open positions", icon: Wallet, tone: "green" },
  ];
  const platforms = [ { title: "Deriv Options", icon: Zap, tone: "deriv", description: "Trade Deriv synthetic indices and currencies with options.", href: "/options", match: "options" }, { title: "Deriv MT5", icon: TrendingUp, tone: "deriv", description: "Synthetic indices, Forex & currencies, Gold/metals and other supported markets.", href: "/connections", match: "deriv" }, { title: "Weltrade MT5", icon: Activity, tone: "weltrade", description: "Forex, Gold, Indices, SyntX and more.", href: "/weltrade", match: "weltrade" } ];
  return <div className="trading-overview">
    <aside className="overview-sidebar">
      <Link to="/" className="overview-brand"><img src="/botvio-logo.png" alt="Botvio" width="145" height="48" /><span>AI TRADING FOR A SMARTER YOU</span></Link>
      <nav aria-label="Dashboard navigation">{links.map(([label, href, Icon], index) => <Button key={label} asChild variant="ghost" className={`overview-nav-link ${index === 0 ? "is-active" : ""}`}><Link to={href}><Icon size={20} /><span>{label}</span></Link></Button>)}</nav>
      <Button asChild variant="outline" className="overview-plan"><Link to="/my-products"><Crown size={24} /><span><strong>{props.access.length ? "My trading access" : "Explore plans"}</strong><small>{props.access.length ? `${props.access.length} active subscriptions` : "Hubs, signals & robots"}</small></span><ChevronRight size={16} /></Link></Button>
    </aside>
    <div className="overview-workspace">
      <header className="overview-topbar">
        <form className="overview-search" onSubmit={event => { event.preventDefault(); const found = links.find(([label]) => label.toLowerCase().includes(search.toLowerCase().trim())); if (search.trim()) navigate(found?.[1] ?? `/signals`); }}><Search size={16} /><input aria-label="Search dashboard" placeholder="Search markets, providers, or features…" value={search} onChange={event => setSearch(event.target.value)} /></form>
        <div className="overview-user">{user && <NotificationBell />}<DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" className="overview-profile"><span className="overview-avatar">{name.slice(0, 2).toUpperCase()}</span><span>{name}</span><ChevronRight size={14} /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link to="/settings"><Settings size={16} className="mr-2" />Settings</Link></DropdownMenuItem><DropdownMenuItem onClick={() => signOut()}><LogOut size={16} className="mr-2" />Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
      </header>
      <main className="overview-main">
        <div className="overview-heading"><div><h1>Trading Overview</h1><p>Your subscriptions, connections and live positions in one place.</p></div><div className="overview-date">{new Date().toLocaleDateString("en-GB", { weekday: "short", day: "numeric", month: "short", year: "numeric", timeZone: "UTC" })}<span>UTC</span></div></div>
        {props.children || <>
          <section className="overview-metrics" aria-label="Account summary">{metrics.map(({ title, value, description, icon: Icon, tone }) => <div className={`overview-metric tone-${tone}`} key={title}><span className="overview-icon"><Icon size={27} /></span><div><p>{title}</p><strong>{value}</strong><small>{description}</small></div></div>)}</section>
          <section><div className="overview-section-heading"><h2>Your trading access</h2><Button asChild variant="link"><Link to="/my-products">View all subscriptions <ArrowRight size={14} /></Link></Button></div>
            {props.accessLoading ? <p className="overview-state">Loading your subscriptions…</p> : props.accessError ? <div className="overview-state">Your access could not be loaded. <Button variant="outline" size="sm" onClick={props.retryAccess}>Retry</Button></div> : !props.access.length ? <div className="overview-state">No active subscriptions yet. <Button asChild variant="link"><Link to="/marketplace">Explore products <ArrowRight size={14} /></Link></Button></div> : <div className="overview-access-grid">{props.access.map(item => {
              const robot = /robot/.test(item.slug ?? ""); const weltrade = /weltrade/.test(item.slug ?? ""); const tone = weltrade ? "gold" : robot ? "cyan" : "green"; const Icon = robot ? Bot : weltrade ? Layers3 : TrendingUp;
              const days = item.endsAt ? Math.max(0, Math.ceil((new Date(item.endsAt).getTime() - Date.now()) / 86400000)) : null;
              return <Link to={item.href} className={`overview-access tone-${tone} art-${robot ? "robot" : weltrade ? "gold" : "chart"}`} key={item.id}><img src={accessArt} width={1536} height={512} loading="lazy" alt="" /><div className="overview-access-content"><span className="overview-icon"><Icon size={29} /></span><div><h3>{item.name}</h3><p>{robot ? "Automated trading with AI." : weltrade ? "Forex, Gold, Indices and SyntX." : "Your trading hubs and signals."}</p><span className={`overview-status ${days != null && days <= 14 ? "expiring" : ""}`}>{days != null && days <= 14 ? `Expires in ${days} days` : "Active"}</span></div></div><footer><span>Signals Access · {robot ? "Trading" : "Market analysis"}</span><ChevronRight size={15} /></footer></Link>;
            })}</div>}
          </section>
          <section><div className="overview-section-heading"><h2>Trading connections</h2><Button asChild variant="link"><Link to="/connections">Manage accounts <ArrowRight size={14} /></Link></Button></div><div className="overview-connections">{platforms.map(platform => { const matches = platform.match === "options" ? [] : props.accounts.filter(a => `${a.broker} ${a.server}`.toLowerCase().includes(platform.match)); const isConnected = matches.some(a => a.connection_status === "connected" || a.tradecopy_active); const Icon = platform.icon; return <div className="overview-connection" key={platform.title}><span className={`overview-broker-icon ${platform.tone}`}><Icon size={28} /></span><div><div className="overview-connection-title"><h3>{platform.title}</h3>{platform.match !== "options" && <span className={`overview-status ${isConnected ? "" : "disconnected"}`}>{props.accountsLoading ? "Checking…" : isConnected ? "Connected" : "Connect account"}</span>}</div><p>{platform.description}</p></div><Button asChild variant="ghost" size="icon" className="overview-connection-settings"><Link to={platform.match === "options" ? "/options" : "/connections"} aria-label={`Manage ${platform.title}`} title={`Manage ${platform.title}`}><Settings size={16} /></Link></Button><Link className="overview-connection-arrow" to={platform.href} aria-label={`Open ${platform.title}`}><ChevronRight size={17} /></Link></div>; })}</div>{props.accountsError && <div className="overview-state">{props.accountsError} <Button size="sm" variant="outline" onClick={props.retryAccounts}>Retry</Button></div>}</section>
          <section><div className="overview-section-heading"><h2>Open trades · Live positions</h2><div className="flex items-center gap-2">{props.anyMock && <span className="overview-status expiring">TEST MODE — not broker data</span>}<Button variant="ghost" size="icon" onClick={props.retryPositions} aria-label="Refresh open trades" title="Refresh open trades"><Activity size={16} /></Button><Button asChild variant="link"><Link to="/trade-history">View full history <ArrowRight size={14} /></Link></Button></div></div>{props.positionError}<div className="overview-table-wrap"><table><thead><tr>{["Broker", "Market", "Side", "Volume", "Entry Price", "Current Price", "Floating P/L", "Status"].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{props.positionLoading ? <tr><td colSpan={8}>Checking open positions…</td></tr> : props.positions.length ? props.positions.map(position => <tr key={position.key}><td>{position.broker}</td><td>{position.symbol}</td><td className={position.side.includes("BUY") ? "overview-positive" : position.side.includes("SELL") ? "overview-negative" : ""}>{position.side}</td><td>{formatValue(position.volume)}</td><td>{formatValue(position.entry)}</td><td>{formatValue(position.current)}</td><td className={Number(position.pnl) >= 0 ? "overview-positive" : "overview-negative"}>{position.pnl == null || !Number.isFinite(Number(position.pnl)) ? "—" : formatMoney(Number(position.pnl))}</td><td><span className={`overview-status ${position.mock ? "expiring" : ""}`}>{position.mock ? "Test" : "Open"}</span></td></tr>) : <tr><td colSpan={8}>{props.positionError ? "Open positions unavailable" : props.accounts.length ? "No trades currently running" : "No TradeCopy account connected"}</td></tr>}</tbody></table></div><p className="overview-footnote">Only broker-returned positions and prices are shown. Test positions are excluded from account totals.</p></section>
          <section><div className="overview-section-heading"><h2>Quick actions</h2></div><div className="overview-quick-grid">{[{ label: "Browse hubs", detail: "Explore market hubs and plans.", href: "/marketplace", icon: Layers3, tone: "green" }, { label: "View signals", detail: "Get the latest trading signals.", href: "/signals", icon: BarChart3, tone: "cyan" }, { label: "Follow a provider", detail: "Discover and copy providers.", href: "/copy-trading", icon: Users, tone: "gold" }, { label: "Open Botvio Robot", detail: "Manage your automated trading.", href: "#robot-controls", icon: Bot, tone: "neutral" }].map(({ label, detail, href, icon: Icon, tone }) => <Button key={label} asChild variant="outline" className={`overview-quick tone-${tone}`}>{href.startsWith("#") ? <a href={href}><span className="overview-icon"><Icon size={26} /></span><span><strong>{label}</strong><small>{detail}</small></span><ChevronRight size={16} /></a> : <Link to={href}><span className="overview-icon"><Icon size={26} /></span><span><strong>{label}</strong><small>{detail}</small></span><ChevronRight size={16} /></Link>}</Button>)}</div></section>
          <details id="robot-controls" className="overview-details"><summary>Robot execution master & linked accounts</summary><div className="space-y-4 pt-4">{props.accounts.map(a => <div className="overview-account-row" key={a.id}><span><strong>{a.label || a.broker || "Trading account"}</strong><small>{[a.broker, a.server, a.login_id, a.account_role, a.environment].filter(Boolean).join(" · ")}</small></span><span>{a.connection_status || "Not connected"}</span></div>)}{props.robotControls}</div></details>
        </>}
      </main>
    </div>
  </div>;
}
