// Persist a live gold signal generated by the in-browser live engine.
// Uses service role to bypass RLS (live engine has no user role).
// Throttled server-side: max 1 active per direction per 30 minutes.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface Body {
  symbol?: string;
  direction: "BUY" | "SELL";
  entry_price: number;
  confidence: number;
  reason?: string;
  strategy?: string;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const body: Body = await req.json();
    if (!body || (body.direction !== "BUY" && body.direction !== "SELL")) {
      return new Response(JSON.stringify({ error: "invalid direction" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (!body.entry_price || !isFinite(body.entry_price)) {
      return new Response(JSON.stringify({ error: "invalid entry_price" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const conf = Math.max(0, Math.min(100, Math.round(body.confidence ?? 0)));
    if (conf < 65) {
      return new Response(JSON.stringify({ skipped: "low_confidence" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const symbol = body.symbol || "XAUUSD";
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Throttle: skip if same-direction active signal exists in last 30 min
    const since = new Date(Date.now() - 30 * 60 * 1000).toISOString();
    const { data: existing } = await supabase
      .from("trading_signals")
      .select("id")
      .eq("symbol", symbol)
      .eq("status", "ACTIVE")
      .eq("direction", body.direction)
      .gte("created_at", since)
      .limit(1);

    if (existing && existing.length > 0) {
      return new Response(JSON.stringify({ skipped: "throttled", id: existing[0].id }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const price = body.entry_price;
    const isBuy = body.direction === "BUY";
    const tp = +(isBuy ? price * 1.005 : price * 0.995).toFixed(2);
    const sl = +(isBuy ? price * 0.997 : price * 1.003).toFixed(2);
    const expiresAt = new Date(Date.now() + 60 * 60 * 1000).toISOString(); // 1h TTL

    const { data, error } = await supabase
      .from("trading_signals")
      .insert({
        symbol,
        direction: body.direction,
        entry_price: +price.toFixed(2),
        stop_loss: sl,
        take_profit: tp,
        timeframe: "M5",
        category: "commodity",
        broker: ["exness", "deriv", "weltrade"],
        confidence: conf,
        reason: body.reason || `Live engine signal (${body.strategy || "Botvio"})`,
        strategy_name: `Botvio Live · ${body.strategy || "Auto"}`,
        status: "ACTIVE",
        is_manual: false,
        expires_at: expiresAt,
      })
      .select("id")
      .single();

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    return new Response(JSON.stringify({ ok: true, id: data?.id }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
