// Persist a live signal generated by the in-browser live engine.
// Uses service role to bypass RLS (live engine has no user role).
// Throttle window matches the chosen timeframe (M1 = 1 min, M5 = 5 min).
// Auto-expires after 1 min (M1) or 5 min (M5) so users don't enter late.
//
// SCALPING TP/SL LOGIC:
//  - Pulls recent candles from Deriv WS to compute support/resistance.
//  - BUY  → TP = nearest resistance above price, SL = nearest support below.
//  - SELL → TP = nearest support below price,    SL = nearest resistance above.
//  - Capped by candle-count distance:
//      M1 → TP within ~3-5 candles of avg range
//      M5 → TP within ~1-3 candles of avg range
//  - Falls back to tight % distances if WS lookup fails.

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface Body {
  symbol?: string;
  direction: "BUY" | "SELL";
  entry_price: number;
  confidence: number;
  reason?: string;
  strategy?: string;
  category?: string;
  timeframe?: "M1" | "M5";
}

// Symbol → Deriv WS symbol for S/R lookup.
function toDerivSymbol(s: string): string | null {
  const u = s.toUpperCase();
  if (u.includes("XAU") || u === "GOLD") return "frxXAUUSD";
  if (u.includes("XAG") || u === "SILVER") return "frxXAGUSD";
  if (u.includes("BTC")) return "cryBTCUSD";
  if (u.includes("ETH")) return "cryETHUSD";
  if (/^[A-Z]{6}$/.test(u)) return `frx${u}`;
  return null;
}

// Pricing fallback profile (used when S/R lookup fails).
function pricingProfile(symbol: string, tf: "M1" | "M5"): {
  tpPct: number; slPct: number; decimals: number; category: string;
} {
  const s = symbol.toUpperCase();
  const scale = tf === "M1" ? 0.4 : 1.0;
  let base = { tpPct: 0.0020, slPct: 0.0015, decimals: 4, category: "other" };

  if (s.includes("BTC")) base = { tpPct: 0.0040, slPct: 0.0028, decimals: 1, category: "crypto" };
  else if (s.includes("ETH")) base = { tpPct: 0.0045, slPct: 0.0030, decimals: 2, category: "crypto" };
  else if (s.includes("XAU") || s.includes("GOLD")) base = { tpPct: 0.0018, slPct: 0.0012, decimals: 2, category: "gold" };
  else if (s.includes("XAG") || s.includes("SILVER")) base = { tpPct: 0.0030, slPct: 0.0020, decimals: 3, category: "commodities" };
  else if (/^[A-Z]{6}$/.test(s)) base = { tpPct: 0.0015, slPct: 0.0010, decimals: 5, category: "forex" };

  return { ...base, tpPct: base.tpPct * scale, slPct: base.slPct * scale };
}

interface Candle { open: number; high: number; low: number; close: number; epoch: number; }

// Fetch last N candles from Deriv WS (one-shot, no subscription).
async function fetchCandles(derivSymbol: string, granularity: number, count = 60): Promise<Candle[]> {
  const appId = Deno.env.get("DERIV_APP_ID") || "1089";
  const url = `wss://ws.derivws.com/websockets/v3?app_id=${appId}`;
  return new Promise((resolve) => {
    let done = false;
    const finish = (out: Candle[]) => { if (!done) { done = true; try { ws.close(); } catch { /* noop */ } resolve(out); } };
    const timer = setTimeout(() => finish([]), 4000);
    let ws: WebSocket;
    try { ws = new WebSocket(url); } catch { clearTimeout(timer); resolve([]); return; }
    ws.onopen = () => {
      ws.send(JSON.stringify({
        ticks_history: derivSymbol,
        adjust_start_time: 1,
        count,
        end: "latest",
        granularity,
        style: "candles",
      }));
    };
    ws.onmessage = (e) => {
      try {
        const data = JSON.parse(e.data);
        if (data.error) { clearTimeout(timer); finish([]); return; }
        if (Array.isArray(data.candles)) {
          const arr: Candle[] = data.candles.map((c: any) => ({
            open: Number(c.open), high: Number(c.high), low: Number(c.low),
            close: Number(c.close), epoch: Number(c.epoch),
          }));
          clearTimeout(timer);
          finish(arr);
        }
      } catch { /* ignore */ }
    };
    ws.onerror = () => { clearTimeout(timer); finish([]); };
  });
}

// Find nearest support (below price) and nearest resistance (above price)
// using swing pivots from recent candles.
function findSR(candles: Candle[], price: number): { support: number | null; resistance: number | null; avgRange: number } {
  if (candles.length < 10) return { support: null, resistance: null, avgRange: 0 };
  const pivotsHigh: number[] = [];
  const pivotsLow: number[] = [];
  // 3-bar pivot detection
  for (let i = 2; i < candles.length - 2; i++) {
    const h = candles[i].high, l = candles[i].low;
    if (h > candles[i - 1].high && h > candles[i - 2].high && h > candles[i + 1].high && h > candles[i + 2].high) pivotsHigh.push(h);
    if (l < candles[i - 1].low && l < candles[i - 2].low && l < candles[i + 1].low && l < candles[i + 2].low) pivotsLow.push(l);
  }
  // Add overall recent extremes as a backstop
  const recent = candles.slice(-30);
  pivotsHigh.push(Math.max(...recent.map((c) => c.high)));
  pivotsLow.push(Math.min(...recent.map((c) => c.low)));

  const resistance = pivotsHigh.filter((h) => h > price).sort((a, b) => a - b)[0] ?? null;
  const support = pivotsLow.filter((l) => l < price).sort((a, b) => b - a)[0] ?? null;

  const ranges = candles.slice(-20).map((c) => c.high - c.low);
  const avgRange = ranges.reduce((a, b) => a + b, 0) / Math.max(ranges.length, 1);

  return { support, resistance, avgRange };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const body: Body = await req.json();
    if (!body || (body.direction !== "BUY" && body.direction !== "SELL")) {
      return new Response(JSON.stringify({ error: "invalid direction" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    if (!body.entry_price || !isFinite(body.entry_price)) {
      return new Response(JSON.stringify({ error: "invalid entry_price" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }
    const conf = Math.max(0, Math.min(100, Math.round(body.confidence ?? 0)));
    if (conf < 65) {
      return new Response(JSON.stringify({ skipped: "low_confidence" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const symbol = (body.symbol || "XAUUSD").toUpperCase();
    const timeframe: "M1" | "M5" = body.timeframe === "M1" ? "M1" : "M5";
    const expirySec = timeframe === "M1" ? 60 : 300;
    const profile = pricingProfile(symbol, timeframe);
    const category = body.category || profile.category;

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Throttle: skip if same symbol+direction+timeframe ACTIVE in last `expirySec`
    const since = new Date(Date.now() - expirySec * 1000).toISOString();
    const { data: existing } = await supabase
      .from("trading_signals")
      .select("id")
      .eq("symbol", symbol)
      .eq("status", "ACTIVE")
      .eq("direction", body.direction)
      .eq("timeframe", timeframe)
      .gte("created_at", since)
      .limit(1);

    if (existing && existing.length > 0) {
      return new Response(JSON.stringify({ skipped: "throttled", id: existing[0].id }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const price = body.entry_price;
    const isBuy = body.direction === "BUY";
    const round = (n: number) => +n.toFixed(profile.decimals);

    // ── Compute S/R-based TP/SL with candle-count caps ─────────────
    // M1 → TP within 3-5 candles of avg range; M5 → 1-3 candles.
    const maxCandles = timeframe === "M1" ? 5 : 3;
    const minCandles = timeframe === "M1" ? 3 : 1;

    const derivSym = toDerivSymbol(symbol);
    const granularity = timeframe === "M1" ? 60 : 300;
    let candles: Candle[] = [];
    if (derivSym) {
      try { candles = await fetchCandles(derivSym, granularity, 80); } catch { /* fallback */ }
    }

    let tp: number;
    let sl: number;
    let tpSource = "fallback%";
    let candleDistance: number | null = null;

    if (candles.length >= 15) {
      const { support, resistance, avgRange } = findSR(candles, price);
      const minDist = avgRange * minCandles;
      const maxDist = avgRange * maxCandles;

      if (isBuy) {
        // TP → nearest resistance (capped), SL → nearest support (capped tighter)
        let tpRaw = resistance != null ? resistance - price : maxDist;
        tpRaw = Math.max(minDist, Math.min(maxDist, tpRaw));
        let slRaw = support != null ? price - support : avgRange * 1.5;
        slRaw = Math.max(avgRange * 0.8, Math.min(avgRange * 2.5, slRaw));
        tp = round(price + tpRaw);
        sl = round(price - slRaw);
        candleDistance = +(tpRaw / Math.max(avgRange, 1e-9)).toFixed(1);
        tpSource = resistance != null ? "resistance" : "candle-cap";
      } else {
        // SELL: TP → nearest support, SL → nearest resistance
        let tpRaw = support != null ? price - support : maxDist;
        tpRaw = Math.max(minDist, Math.min(maxDist, tpRaw));
        let slRaw = resistance != null ? resistance - price : avgRange * 1.5;
        slRaw = Math.max(avgRange * 0.8, Math.min(avgRange * 2.5, slRaw));
        tp = round(price - tpRaw);
        sl = round(price + slRaw);
        candleDistance = +(tpRaw / Math.max(avgRange, 1e-9)).toFixed(1);
        tpSource = support != null ? "support" : "candle-cap";
      }
    } else {
      // Fallback: tight % scalping distances
      tp = round(isBuy ? price * (1 + profile.tpPct) : price * (1 - profile.tpPct));
      sl = round(isBuy ? price * (1 - profile.slPct) : price * (1 + profile.slPct));
    }

    const expiresAt = new Date(Date.now() + expirySec * 1000).toISOString();
    const candleNote = candleDistance != null ? ` · ${candleDistance} candle TP` : "";
    const strategyTag = `Botvio Live ${timeframe} · ${body.strategy || "Auto"}${candleNote} · TP@${tpSource}`;
    const reasonText = body.reason
      ? `${body.reason} | ${timeframe} scalp, TP=${tpSource}${candleDistance != null ? ` (~${candleDistance} candles)` : ""}`
      : `Live engine ${timeframe} scalp (${body.strategy || "Botvio"}) — TP at ${tpSource}${candleDistance != null ? ` ~${candleDistance} candles ahead` : ""}`;

    const { data, error } = await supabase
      .from("trading_signals")
      .insert({
        symbol,
        direction: body.direction,
        entry_price: round(price),
        stop_loss: sl,
        take_profit: tp,
        timeframe,
        category,
        broker: ["exness", "deriv", "weltrade"],
        confidence: conf,
        reason: reasonText,
        strategy_name: strategyTag,
        status: "ACTIVE",
        is_manual: false,
        expires_at: expiresAt,
        expiry_seconds: expirySec,
      })
      .select("id")
      .single();

    if (error) {
      return new Response(JSON.stringify({ error: error.message }), {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Mirror into signals_history immediately (RUNNING) so the public
    // performance tracker shows the signal lifecycle from the start.
    await supabase.from("signals_history").insert({
      signal_id: data?.id,
      pair: symbol,
      signal_type: body.direction,
      entry_price: round(price),
      take_profit: tp,
      stop_loss: sl,
      result: "RUNNING",
      source: "BOT",
      strategy_name: strategyTag,
    });

    // ── Fan out: auto-execute on opted-in users' Deriv accounts ───────
    // Opt-in is OFF by default (auto_trade_settings.enabled = false).
    // Respects user's account_type (demo/real), stake, multiplier, min_confidence,
    // daily kill-switch and per-asset whitelist. Live-engine signals only.
    const autoExecResults = await autoExecuteForOptedInUsers(supabase, {
      symbol,
      direction: body.direction,
      confidence: conf,
      entry: round(price),
      sl,
      tp,
      timeframe,
      signalId: data?.id,
    }).catch((e) => {
      console.error("[persist-live-gold-signal] fan-out error:", e);
      return { attempted: 0, filled: 0, error: String(e) };
    });

    return new Response(JSON.stringify({
      ok: true,
      id: data?.id,
      timeframe,
      expires_at: expiresAt,
      tp_source: tpSource,
      candle_distance: candleDistance,
      auto_exec: autoExecResults,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    return new Response(JSON.stringify({ error: String(e) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
