// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-signals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-signals.ts
var list_signals_default = defineTool({
  name: "list_signals",
  title: "List trading signals",
  description: "List the most recent Botvio trading signals visible to the signed-in user, newest first. Optionally filter by symbol, direction or status.",
  inputSchema: {
    symbol: z.string().trim().min(1).optional().describe("Filter by instrument, e.g. XAUUSD or R_100."),
    direction: z.enum(["BUY", "SELL"]).optional().describe("Filter by signal direction."),
    status: z.string().trim().min(1).optional().describe("Filter by signal status, e.g. approved or pending."),
    limit: z.number().int().min(1).max(50).default(10).describe("Number of signals to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ symbol, direction, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("trading_signals").select(
      "id,symbol,direction,timeframe,strategy_name,entry_price,stop_loss,take_profit,confidence,status,outcome,created_at,expires_at,reason"
    ).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (symbol) query = query.ilike("symbol", symbol);
    if (direction) query = query.eq("direction", direction);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { signals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-signal.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_signal_default = defineTool2({
  name: "get_signal",
  title: "Get signal details",
  description: "Fetch one Botvio trading signal by id, including entry, stop-loss, take-profit, confidence and settlement details.",
  inputSchema: { id: z2.string().uuid().describe("The trading signal id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trading_signals").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError(`No signal found with id ${id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { signal: data }
    };
  }
});

// src/lib/mcp/tools/list-my-trades.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_my_trades_default = defineTool3({
  name: "list_my_trades",
  title: "List my trades",
  description: "List the signed-in user's own trade executions on Botvio (stake, fill price, status and P&L), newest first.",
  inputSchema: {
    status: z3.string().trim().min(1).optional().describe("Filter by execution status, e.g. OPEN, RUNNING or CLOSED."),
    limit: z3.number().int().min(1).max(50).default(10).describe("Number of executions to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("executions").select("id,broker_ref,stake_or_lot,fill_price,pnl,status,created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { executions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-performance.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var my_performance_default = defineTool4({
  name: "my_performance",
  title: "My trading performance",
  description: "Summarise the signed-in user's Botvio trading performance over a recent window: trade count, wins, losses, win rate and net P&L.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).default(30).describe("Look-back window in days (1-365).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const window = days ?? 30;
    const since = new Date(Date.now() - window * 24 * 60 * 60 * 1e3).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("executions").select("pnl,status,created_at").eq("user_id", ctx.getUserId()).gte("created_at", since).limit(1e3);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const settled = rows.filter((r) => typeof r.pnl === "number");
    const wins = settled.filter((r) => (r.pnl ?? 0) > 0).length;
    const losses = settled.filter((r) => (r.pnl ?? 0) < 0).length;
    const netPnl = settled.reduce((sum, r) => sum + (r.pnl ?? 0), 0);
    const summary = {
      window_days: window,
      total_executions: rows.length,
      settled_executions: settled.length,
      wins,
      losses,
      win_rate_percent: settled.length ? Math.round(wins / settled.length * 1e3) / 10 : null,
      net_pnl: Math.round(netPnl * 100) / 100,
      open_executions: rows.filter((r) => r.status && !["CLOSED", "closed"].includes(r.status)).length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tqqkzeblmjapgbnsbtgw";
var mcp_default = defineMcp({
  name: "botvio-forex-copy-trading-automated-trading-p2p",
  title: "BOTVIO Forex | Copy Trading, Automated Trading & P2P",
  version: "0.1.0",
  instructions: "Tools for BOTVIO, an AI trading platform. Use `list_signals` and `get_signal` to read trading signals, `list_my_trades` for the signed-in user's executions, and `my_performance` for their win rate and net P&L. All tools act as the authenticated Botvio user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_signals_default, get_signal_default, list_my_trades_default, my_performance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
